### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by MunavarAY** [MunavarAY/SEBC#2]

**Comment by MunavarAY** [comment]
CM Install Lab - Prepare your instances - Completed

**Comment by mfernest** [comment]
Can you comment on your progress up to this point?

**Comment by MunavarAY** [comment]
Mike, I am not willing to give up just yet. I have gone through 5 rounds of CM installation from scratch. someway or the other it is breaking in between and not giving be a clear clusters with 5 set of servers.


Mostly it is happening due to Java incompatibility issues.  somehow open JDK is getting installed into the servers. I am installing on Centos 7.2


Going through the next CM installation attempt now.


And I can see that, I may need to sit for the challenge lab again. I am willing to give it a go tomorrow morning.


Thanks

Munavar

________________________________

**Comment by mfernest** [comment]
I appreciate all your effort and persistence during the week! It can be quite difficult to learn with so many roadblocks.

I can't recall now if we discussed OpenJDK as a blocker to the installation process, but it certainly can be. Please refer to Cloudera's documentation, in any event: it will tell you OpenJDK is not supported. That said, I am surprised you encountered so much trouble just getting started.

**Comment by MunavarAY** [comment]
Thanks for your kind email. Yes I am aware that only oracle jdk is supported and not open jdk.

I would love to go through the installation process again if there is any cheaper or free options available to spin up servers.



Sent with BlackBerry Work (www.blackberry.com)
________________________________
